## `dot identities`.

# Renders the laptop-side identity config devbox leaves to you (devbox
# docs/git.md, "Laptop install") with devbox's own renderer, so both machines
# derive from one ~/.config/devbox/identities.conf. `devbox doctor laptop` reads
# these with `git config --global`, which does not follow [include] - hence
# a generated ~/.gitconfig rather than an include of a generated file.
# $1: output directory standing in for $HOME.
render_identities() (
  local out="$1" slug default dir url
  # shellcheck source=/dev/null
  . "$IDENTITIES_LIB"
  # `||`, not set -e: the caller tests this function, which disables errexit.
  di_check >/dev/null || exit 1
  default="$(di_default)"
  mkdir -p "$out/.config/git/identities" "$out/.ssh/config.d"
  {
    printf '# Generated by `dot identities` from ~/.config/devbox/identities.conf: edit\n'
    printf '# that file and re-run. Shared settings: ~/.config/git/config (dotfiles).\n'
    di_render_user_block "$default"
    printf '[gpg]\n\tformat = ssh\n[gpg "ssh"]\n\tprogram = %s\n\tallowedSignersFile = %s/.ssh/allowed_signers\n' "$OP_SSH_SIGN" "$HOME"
    printf '[commit]\n\tgpgsign = true\n[tag]\n\tgpgsign = true\n'
    # Trees, shortest first: among matching includes the last one read wins.
    for slug in $(di_dir_slugs); do
      dir="$(di_raw "$slug" dir)"
      while [ "${dir%/}" != "$dir" ]; do dir=${dir%/}; done
      printf '[includeIf "gitdir:%s/"]\n\tpath = ~/.config/git/identities/user-%s.gitconfig\n' "$dir" "$slug"
      di_render_user_gitconfig "$slug" >"$out/.config/git/identities/user-$slug.gitconfig"
    done
    # Owners after trees, so an org's identity wins wherever it is cloned.
    for slug in $(di_slugs); do
      [ -n "$(di_get "$slug" orgs)" ] || continue
      for url in $(di_org_urls "$slug"); do
        printf '[includeIf "hasconfig:remote.*.url:%s"]\n\tpath = ~/.config/git/identities/org-%s.gitconfig\n' "$url" "$slug"
      done
      di_render_org_gitconfig "$slug" >"$out/.config/git/identities/org-$slug.gitconfig"
    done
  } >"$out/.gitconfig"
  di_render_ssh_config >"$out/.ssh/config.d/identities"
  # The public halves that select a 1Password key per host (IdentityFile *.pub
  # + IdentitiesOnly); the registry carries them, so a new Mac needs no export.
  for slug in $(di_slugs); do
    printf '%s\n' "$(di_get "$slug" pubkey)" >"$out/.ssh/id_$slug.pub"
    printf '%s\n' "$(di_get "$slug" signing_pubkey)" >"$out/.ssh/signing_$slug.pub"
  done
  # devbox renders allowed_signers from the signing_*.pub files under $HOME;
  # point it at the ones just rendered, so a first run is not left empty.
  HOME="$out" di_render_allowed_signers >"$out/.ssh/allowed_signers"
)

# Same key, maybe another comment: not worth rewriting a .pub over.
same_file() {
  case "$1" in
  *.pub) [ -f "$3" ] && [ "$(awk '{print $1, $2}' "$2")" = "$(awk '{print $1, $2}' "$3")" ] ;;
  *) cmp -s "$2" "$3" ;;
  esac
}

# Writes what render_identities produces where it differs from ~.
# $1: 1 to only report stale files, returning 1 if any.
identities_sync() {
  local check="${1:-0}" tmp rel stale=0 dst mode
  [ -r "$IDENTITIES_LIB" ] || die "devbox-identities missing: run \`./bin/devbox agent install\` in $(tilde "$DEVBOX_DIR")"
  [ -r "$HOME/.config/devbox/identities.conf" ] || die 'no ~/.config/devbox/identities.conf: `dot vault pull` restores it'
  tmp="$(mktemp -d)"
  if ! render_identities "$tmp"; then
    rm -rf "$tmp"
    die 'identities.conf does not validate: devbox-identities check'
  fi
  for rel in $(cd "$tmp" && find . -type f | sed 's|^\./||'); do
    dst="$HOME/$rel"
    same_file "$rel" "$tmp/$rel" "$dst" && continue
    stale=$((stale + 1))
    if [ "$check" = 1 ]; then
      info "stale ~/$rel"
      continue
    fi
    # A hand-written ~/.gitconfig predates `dot identities`: keep a copy once.
    if [ "$rel" = .gitconfig ] && [ -f "$dst" ] && ! head -1 "$dst" | grep '`dot identities`' >/dev/null; then
      mkdir -p "$HOME/.dotfiles-backup"
      cp -p "$dst" "$HOME/.dotfiles-backup/gitconfig.$(date +%Y%m%d-%H%M%S)"
      info "backed up the hand-written ~/.gitconfig to ~/.dotfiles-backup/"
    fi
    mode=600
    case "$rel" in *.pub) mode=644 ;; esac
    mkdir -p "$(dirname "$dst")"
    install -m "$mode" "$tmp/$rel" "$dst"
    info "wrote ~/$rel"
  done
  rm -rf "$tmp"
  if [ "$check" = 1 ]; then
    [ $stale = 0 ]
    return
  fi
  ok "identity config current ($stale file(s) updated)"
}
